### ISSUE TITLE
build/check problems with ade4 and friends

### ISSUE THREAD

**Issue by friendly** [friendly/Guerry#3]
Just re-checked with win-builder and the updated ade4 packages.  Now I get errors from re-building the MultiSpat vignette.  Don't know what to do about this.

    Error(s) in re-building vignettes:
    --- re-building 'MultiSpat.Rmd' using rmarkdown

    Attaching package: 'adegraphics'

    The following objects are masked from 'package:ade4':

        kplotsepan.coa, s.arrow, s.class, s.corcircle, s.distri, s.image,
        s.label, s.logo, s.match, s.traject, s.value, table.value,
        triangle.class

    Loading required package: spData
    To access larger datasets in this package, install the spDataLarge
    package with: `install.packages('spDataLarge',
    repos='https://nowosad.github.io/drat/', type='source')`
    Loading required package: sf
    Linking to GEOS 3.9.1, GDAL 3.2.1, PROJ 7.2.1

    Attaching package: 'spdep'

    The following object is masked from 'package:ade4':

        mstree

    Attaching package: 'adespatial'

    The following object is masked from 'package:ade4':

        multispati

    pandoc-citeproc: reference PCAIV not found
    --- finished re-building 'MultiSpat.Rmd'

**Comment by friendly** [comment]
I'm going to move the vignettes to a folder `vignettes-new` (in `.Rbuildignore`) until this is sorted out.  Need to get the Guerry package back on CRAN

**Comment by sdray** [comment]
Sorry, It was a simple typo (inserted a link instead of a simple text). It is now corrected and should work

**Comment by sdray** [comment]
I think that we can now deal again with the vignettes folder

**Comment by friendly** [comment]
OK, thanks.  Surprised this didn't arise before.
There is also a missing reference for PCAIV that I commented out in your vignette (now in vignettes-new/)

I submitted v 1.7.3 w/o vignettes, so will wait until this is sorted out.

**Comment by sdray** [comment]
Yes, strange. In my local version, there was a `\citep `LaTex command that I forgot to remove. Then, the text `PCAIV` has been wrongly set as a link `@PCAIV`. I just remove the `@` sugn and this should work now. Sorry for that and I do not understand why it worked before. This new version should solve the issue. I think that we can try to move `vignettes-new` to `vignettes` as the bug has been corrected

**Comment by friendly** [comment]
OK, I'll restore MultiSpat.Rnw and test again.  I'll need to bump the pkg version before resubmitting.

I assume I should just ignore the messages about functions in ade4 masked by adegraphics.

**Comment by sdray** [comment]
Yes, do not worry about warnings. We replaced some functions of ade4 by new ones (with the same name) in adegraphics but keep former functions in ade4 to ensure comptability with other packages.

**Comment by friendly** [comment]
Guerry 1.7.4 now checks OK on win-builder.  Preparing to resubmit.  Thx again for your continued contribution with this.

**Comment by friendly** [comment]
Guerry 1.7.4 is on its way to CRAN! 
This issue is now closed.
